name: Run Tests and Lint

on: push

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod
    - name: Install Task
      run: |
        curl -sL https://taskfile.dev/install.sh | sh
        sudo mv ./bin/task /usr/local/bin
    - name: Cache code
      uses: actions/cache@v3
      with:
        path: |
          ~/go/pkg/mod              # Module download cache
          ~/.cache/go-build         # Build cache (Linux)
          ~/Library/Caches/go-build # Build cache (Mac)
          '%LocalAppData%\go-build' # Build cache (Windows)
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: Setup golangci-lint
      uses: golangci/golangci-lint-action@v2
    - name: Run Tests
      run: task test
    - name: Run Lint
      run: task lint
